# SEO settings
title: "crossroads lab."
title2: "" # default: ""
description: "connecting the dots"
keywords: "UX, IU, Interface, CoderDojo, kids, "
url: https://crssrds.jp # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-36921937-1
repo: http://github.com/kwaka1208/kwaka1208.github.io
twitter_username: "kwaka1208"
comments: false 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

gems:
  - jekyll-sitemap

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "crossroads lab."
  job      : "connecting the dots"
  bio      : "I love self brewed coffee, bookstore, Starbucks, MUJI and good things."
  thumb    : https://avatars.githubusercontent.com/kwaka1208
  url      : https://crssrds.jp
  github   : https://github.com/kwaka1208
  twitter  : https://twitter.com/kwaka1208
  facebook : https://www.facebook.com/kwaka1208
  linkedin : https://linkedin.com/in/kwaka1208

# social settings
og_locale: "ja_JP"
twitter_card: "summary_large_image"
twitter_site: "@kwaka1208"

Plugin:
  - bourbon
  - jekyll-paginate
  - jekyll-seo-tag

# navbar pages
navbar:
  - slug : aboutme
    title: Aboutme
  - slug : blog
    title: Blog

kramdown:
  auto_ids: false

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
