basic_settings:
  site_title: crossroads lab.
  favicon_image: /assets/icons/favicon/favicon.ico

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'home'
      url: '/'
    - title: 'note'
      url: '/note/'
    - title: 'talk'
      url: '/talk/'
    - title: 'about'
      url: '/aboutme/'
    - title: 'contact'
      url: '/contact/'

footer_settings:
  footer_tagline: connecting the dots.

hero_settings:
  overlay_opacity: 0

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/mqkwzrgw'
  confirmation_url: '/complete'
  email_subject: 'お問い合わせフォームからの連絡'
  send_button_text: '送信'

social_settings:
  twitter_url: 'https://twitter.com/kwaka1208'
  facebook_url: 'https://www.facebook.com/kwaka1208/'
  instagram_url: 'https://www.instagram.com/kwaka1208/'
  github_url: 'https://github.com/kwaka1208'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: 'http://amzn.to/2PDXseF'
  apple_url: 'https://podcasts.apple.com/jp/podcast/id1494990721'
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: 'https://open.spotify.com/show/3gBCLGnpFLSsuSZeepOISq'
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#3498db'
  border_color: '#dddddd'
  # hero_background_color: '#132930'
  hero_background_color: '#156da5'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,400,600,700" rel="stylesheet">'
  title_font: '"Noto Sans JP", sans-serif'
  body_font: '"Noto Sans JP", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 28
    medium_size: 36
    large_size: 36
    weight: 600
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 18
    medium_size: 26
    large_size: 30
    weight: 600
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 16
    medium_size: 22
    large_size: 26
    weight: 600
    letter_spacing: -0.02
    line_height: 1.4
  h4:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.8
  blockquote: 
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

cover:
  default: /assets/images/cover/default.png
